var U=[],M=[],O=[],SA=[],TX=[],SR={},IR={},UR={},isLocked=false,loggedIn=false;
function $(i){return document.getElementById(i)}
function doLogin(){var u=$('auser').value,p=$('apass').value;fetch('/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({user:u,pass:p})}).then(r=>r.json()).then(d=>{if(d.success){loggedIn=true;localStorage.setItem('sct','1');$('loginScreen').style.display='none';$('mainApp').style.display='block';rf()}else{$('lerr').style.display='block';setTimeout(()=>$('lerr').style.display='none',3000)}})}
function doLogout(){loggedIn=false;localStorage.removeItem('sct');$('loginScreen').style.display='flex';$('mainApp').style.display='none';$('auser').value='';$('apass').value=''}
function checkSession(){if(localStorage.getItem('sct')==='1'){$('loginScreen').style.display='none';$('mainApp').style.display='block';loggedIn=true;rf()}$('ipaddr').textContent=location.host}
function sw(n){for(var i=0;i<5;i++){$('p'+i).className=i==n?'p a':'p';document.querySelectorAll('.t')[i].className=i==n?'t a':'t'}if(n==1)lu();if(n==2)lm();if(n==3)lo();if(n==4)lrp()}
function sm(i){$(i).className='m s'}
function hm(i){$(i).className='m'}
function rf(){lu();lm();lo();lsa();gls()}
function gls(){fetch('/api/system/status').then(r=>r.json()).then(d=>{isLocked=d.locked;$('lockBanner').style.display=d.locked?'block':'none';$('lockMsg').textContent=d.message||'System Closed';$('lockBtn').innerHTML=d.locked?'&#128275; Unlock System':'&#128274; Lock System';$('lockBtn').className=d.locked?'b bg':'b br'})}
function toggleLock(){if(isLocked){fetch('/api/system/unlock',{method:'POST'}).then(()=>gls())}else{var msg=prompt('Lock message (optional):','Canteen Closed');if(msg!==null)fetch('/api/system/lock',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:msg||'System Closed'})}).then(()=>gls())}}
function lu(){fetch('/api/users').then(r=>r.json()).then(d=>{U=d;var h='';d.forEach((u,i)=>{h+='<tr><td><code>'+u.uid+'</code></td><td><b>'+u.name+'</b></td><td>&#8377;'+u.balance.toFixed(0)+'</td><td>&#8377;'+u.creditLimit.toFixed(0)+'</td><td><button class="b by" onclick="edU('+i+')">&#9998;</button><button class="b bg" onclick="rch('+i+')">+&#8377;</button><button class="b br" onclick="delU('+i+')">&#128465;</button></td></tr>'});$('ut').innerHTML=h;$('tu').textContent=d.length;$('on').textContent=d.filter(x=>x.online).length})}
function sb(s){if(s==0)return'<span style="background:#6c757d;color:#fff;padding:2px 8px;border-radius:10px;font-size:11px">&#10060; OUT</span>';if(s<10)return'<span style="background:linear-gradient(135deg,#eb3349,#f45c43);color:#fff;padding:2px 8px;border-radius:10px;font-size:11px">&#128308; '+s+'</span>';if(s<25)return'<span style="background:linear-gradient(135deg,#f7971e,#ffd200);color:#333;padding:2px 8px;border-radius:10px;font-size:11px">&#128993; '+s+'</span>';return'<span style="background:linear-gradient(135deg,#56ab2f,#a8e063);color:#fff;padding:2px 8px;border-radius:10px;font-size:11px">&#128994; '+s+'</span>'}
function lm(){fetch('/api/menu').then(r=>r.json()).then(d=>{M=d;var h='';d.forEach((m,i)=>{h+='<tr><td><code>'+m.key+'</code></td><td><b>'+m.name+'</b></td><td>&#8377;'+m.price.toFixed(0)+'</td><td>'+sb(m.stock)+'</td><td><button class="b by" onclick="edM('+i+')">&#9998;</button><button class="b br" onclick="delM('+i+')">&#128465;</button></td></tr>'});$('mt').innerHTML=h;$('tm').textContent=d.length})}
function lo(){fetch('/api/orders').then(r=>r.json()).then(d=>{O=d;var h='',p=0;d.forEach(o=>{if(o.status=='pending')p++;var cls=o.status=='ready'?'o r':o.status=='cancelled'?'o c':'o';h+='<div class="'+cls+'"><b>&#127915; #'+o.id+'</b> - <b>'+o.userName+'</b><span class="st s'+o.status[0]+'">'+o.status.toUpperCase()+'</span><br><span style="font-size:11px;color:#666">&#128337; '+(o.time||'--')+'</span><br>';o.items.forEach(it=>{h+='&#8226; '+it.name+' &times;'+it.qty+'<br>'});h+='<b>&#8377; '+o.total.toFixed(0)+'</b>';if(o.status=='pending')h+='<div style="display:flex;gap:8px;margin-top:12px"><div style="flex:1;background:linear-gradient(135deg,#56ab2f,#a8e063);padding:14px;border-radius:8px;text-align:center;cursor:pointer;color:#fff;font-weight:bold;font-size:16px" onclick="rdy('+o.id+')">&#10004; READY</div><div style="flex:1;background:linear-gradient(135deg,#eb3349,#f45c43);padding:14px;border-radius:8px;text-align:center;cursor:pointer;color:#fff;font-weight:bold;font-size:16px" onclick="cnl('+o.id+')">&#10006; CANCEL</div></div>';h+='</div>'});$('ol').innerHTML=h||'<div style="text-align:center;padding:30px;color:#888">&#127860; No orders yet</div>';$('to').textContent=p});lsa()}
function lsa(){fetch('/api/stock-alerts').then(r=>r.json()).then(d=>{SA=d;var h='',c=0;d.forEach((a,i)=>{if(!a.ack){c++;h+='<div style="background:linear-gradient(135deg,#fff5f5,#ffe0e0);border-left:4px solid #eb3349;padding:12px;margin:8px 0;border-radius:8px;display:flex;justify-content:space-between;align-items:center"><div><b style="color:#eb3349">&#9888; LOW STOCK</b><br><b>['+a.key+']</b> '+a.name+' - Only <b style="color:#eb3349">'+a.stock+'</b> left!</div><button class="b by" onclick="ackSA(\''+a.key+'\')" style="white-space:nowrap">&#10004; Acknowledge</button></div>'}});$('sal').innerHTML=h;$('sa').textContent=c;$('sas').style.background=c>0?'linear-gradient(135deg,#ffe0e0,#ffcccc)':'';if(c>0&&'speechSynthesis'in window){var u=new SpeechSynthesisUtterance('Warning: '+c+' items running low on stock');speechSynthesis.speak(u)}})}
function ackSA(k){fetch('/api/stock-alerts/'+k+'/ack',{method:'POST'}).then(()=>lsa())}
function addU(){var d={uid:$('nuid').value,name:$('nname').value,balance:+$('nbal').value,creditLimit:+$('ncl').value};fetch('/api/users',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(d)}).then(()=>{hm('au');lu()})}
function addM(){var d={key:$('mkey').value.toUpperCase(),name:$('mname').value,price:+$('mprice').value,stock:+$('mstock').value};fetch('/api/menu',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(d)}).then(()=>{hm('am');lm()})}
function edU(i){var u=U[i];$('euid').value=u.uid;$('ename').value=u.name;$('ebal').value=u.balance;$('ecl').value=u.creditLimit;sm('eu')}
function updU(){var d={name:$('ename').value,balance:+$('ebal').value,creditLimit:+$('ecl').value};fetch('/api/users/'+$('euid').value,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(d)}).then(()=>{hm('eu');lu()})}
function delU(i){if(confirm('Delete '+U[i].name+'?'))fetch('/api/users/'+U[i].uid,{method:'DELETE'}).then(()=>lu())}
function rch(i){var a=prompt('Recharge amount:');if(a)fetch('/api/users/'+U[i].uid+'/recharge',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({amount:+a})}).then(()=>lu())}
function edM(i){var s=prompt('New stock for '+M[i].name+':',M[i].stock);if(s!=null){var p=prompt('New price:',M[i].price);if(p!=null)fetch('/api/menu/'+M[i].key,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({stock:+s,price:+p})}).then(()=>lm())}}
function delM(i){if(confirm('Delete '+M[i].name+'?'))fetch('/api/menu/'+M[i].key,{method:'DELETE'}).then(()=>lm())}
function rdy(id){var ord=O.find(o=>o.id==id);fetch('/api/orders/'+id+'/ready',{method:'POST'}).then(()=>{lo();if('speechSynthesis'in window){var u=new SpeechSynthesisUtterance('Order ready for '+(ord?ord.userName:'customer'));speechSynthesis.speak(u)}})}
function cnl(id){if(confirm('Cancel order?'))fetch('/api/orders/'+id+'/cancel',{method:'POST'}).then(()=>lo())}
var scanInterval=null;
function startScan(){$('scanStatus').textContent='Scanning...';$('scanStatus').style.background='#fff3cd';fetch('/api/scan-mode',{method:'POST'});if(scanInterval)clearInterval(scanInterval);scanInterval=setInterval(()=>{fetch('/api/last-scanned').then(r=>r.json()).then(d=>{if(d.uid&&d.uid.length>0){clearInterval(scanInterval);$('suid').value=d.uid;$('scanStatus').textContent='Card found!';$('scanStatus').style.background='#d4edda';$('sname').focus();fetch('/api/clear-scanned',{method:'POST'})}})},1000)}
function addScanned(){var d={uid:$('suid').value,name:$('sname').value,balance:+$('sbal').value,creditLimit:+$('scl').value};if(!d.uid||!d.name){alert('Enter UID and Name');return}fetch('/api/users',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(d)}).then(()=>{$('suid').value='';$('sname').value='';$('sbal').value='0';$('scl').value='0';lu();$('scanStatus').textContent='Added!';$('scanStatus').style.background='#d4edda';setTimeout(()=>{$('scanStatus').textContent='Ready';$('scanStatus').style.background='#f0f0f0'},2000)})}
function sc(){startScan()}
function dl(n,t,c){var a=document.createElement('a');a.href='data:text/'+c+';charset=utf-8,'+encodeURIComponent(t);a.download=n;a.click()}
function dlU(f){if(!U.length)return alert('No users');var t='';if(f=='csv'){t='UID,Name,Balance,CreditUsed,CreditLimit\n';U.forEach(u=>t+=u.uid+','+u.name+','+u.balance+','+u.creditUsed+','+u.creditLimit+'\n');dl('users.csv',t,'csv')}else{t='SMART CANTEEN - USERS\n'+new Date().toLocaleString()+'\n\n';U.forEach(u=>t+='UID: '+u.uid+'\nName: '+u.name+'\nBalance: Rs '+u.balance+'\nCredit Used: Rs '+u.creditUsed+'\nCredit Limit: Rs '+u.creditLimit+'\n---\n');dl('users.txt',t,'plain')}}
function dlM(f){if(!M.length)return alert('No menu');var t='';if(f=='csv'){t='Key,Name,Price,Stock\n';M.forEach(m=>t+=m.key+','+m.name+','+m.price+','+m.stock+'\n');dl('menu.csv',t,'csv')}else{t='SMART CANTEEN - MENU\n'+new Date().toLocaleString()+'\n\n';M.forEach(m=>t+='['+m.key+'] '+m.name+'\nPrice: Rs '+m.price+' | Stock: '+m.stock+'\n---\n');dl('menu.txt',t,'plain')}}
function dlO(f){if(!O.length)return alert('No orders');var t='';if(f=='csv'){t='OrderID,Time,User,Status,Total,Items\n';O.forEach(o=>{var items=o.items.map(i=>i.name+'x'+i.qty).join(';');t+=o.id+','+(o.time||'')+','+o.userName+','+o.status+','+o.total+',"'+items+'"\n'});dl('orders.csv',t,'csv')}else{t='SMART CANTEEN - ORDERS\n'+new Date().toLocaleString()+'\n\n';O.forEach(o=>{t+='Order #'+o.id+' ['+(o.time||'--')+'] ['+o.status.toUpperCase()+']\nUser: '+o.userName+'\n';o.items.forEach(i=>t+='  - '+i.name+' x'+i.qty+'\n');t+='Total: Rs '+o.total+'\n---\n'});dl('orders.txt',t,'plain')}}
function lrp(){ltx();lsr();lir();lur()}
function ltx(){fetch('/api/transactions').then(r=>r.json()).then(d=>{TX=d;var h='';d.slice(0,20).forEach(t=>{var c=t.type=='order'?'#eb3349':t.type=='recharge'?'#56ab2f':'#f7971e';h+='<tr><td style="font-size:11px;color:#666">'+(t.time||'--')+'</td><td><span style="background:'+c+';color:#fff;padding:2px 6px;border-radius:4px;font-size:11px">'+t.type.toUpperCase()+'</span></td><td>'+t.userName+'</td><td>&#8377;'+t.amount.toFixed(0)+'</td><td>'+(t.orderId||'-')+'</td></tr>'});$('txl').innerHTML=h||'<tr><td colspan="5" style="text-align:center;color:#888">No transactions</td></tr>'})}
function lsr(){fetch('/api/reports/sales').then(r=>r.json()).then(d=>{SR=d;$('ts').innerHTML='&#8377;'+d.totalSales.toFixed(0);$('tord').textContent=d.totalOrders;$('trch').innerHTML='&#8377;'+d.totalRecharges.toFixed(0);var h='<div style="display:flex;gap:4px;align-items:flex-end;height:80px">';var mx=Math.max(...d.daily.map(x=>x.sales))||1;d.daily.forEach((x,i)=>{var ht=Math.max(10,x.sales/mx*70);h+='<div style="flex:1;text-align:center"><div style="background:linear-gradient(180deg,#667eea,#764ba2);height:'+ht+'px;border-radius:4px 4px 0 0"></div><div style="font-size:10px;color:#666">D'+(i+1)+'</div></div>'});h+='</div>';$('sc').innerHTML=h;var th='';d.topItems.slice(0,5).forEach((x,i)=>{th+='<div style="display:flex;justify-content:space-between;padding:6px 0;border-bottom:1px solid #eee"><span>'+(i+1)+'. '+x.name+'</span><b>'+x.qty+' sold</b></div>'});$('ti').innerHTML=th||'<div style="color:#888">No sales data</div>'})}
function lir(){fetch('/api/reports/inventory').then(r=>r.json()).then(d=>{IR=d})}
function lur(){fetch('/api/reports/users').then(r=>r.json()).then(d=>{UR=d;var h='';d.topUsers.slice(0,5).forEach((u,i)=>{h+='<div style="display:flex;justify-content:space-between;padding:6px 0;border-bottom:1px solid #eee"><span>'+(i+1)+'. '+u.name+'</span><b>&#8377;'+u.spent.toFixed(0)+' spent</b></div>'});$('ua').innerHTML=h||'<div style="color:#888">No activity data</div>'})}
function dlRp(t){if(t=='sales'){var txt='SALES REPORT\n'+new Date().toLocaleString()+'\n\nTotal Sales: Rs '+SR.totalSales+'\nTotal Orders: '+SR.totalOrders+'\nTotal Recharges: Rs '+SR.totalRecharges+'\n\nDaily Sales:\n';SR.daily.forEach((d,i)=>txt+='Day '+(i+1)+': Rs '+d.sales+' ('+d.orders+' orders)\n');txt+='\nTop Items:\n';SR.topItems.forEach((x,i)=>txt+=(i+1)+'. '+x.name+' - '+x.qty+' sold (Rs '+x.revenue+')\n');dl('sales_report.txt',txt,'plain')}else if(t=='inv'){var txt='INVENTORY REPORT\n'+new Date().toLocaleString()+'\n\n';IR.items.forEach(x=>txt+='['+x.key+'] '+x.name+'\nStock: '+x.stock+' | Sold: '+x.sold+' | Revenue: Rs '+x.revenue+'\n---\n');dl('inventory_report.txt',txt,'plain')}else{var txt='USER ACTIVITY REPORT\n'+new Date().toLocaleString()+'\n\nTop Spenders:\n';UR.topUsers.forEach((u,i)=>txt+=(i+1)+'. '+u.name+' - Rs '+u.spent+' ('+u.orders+' orders)\n');dl('user_activity.txt',txt,'plain')}}
function uclk(){var d=new Date();var days=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'];var months=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];$('cdate').textContent=days[d.getDay()]+', '+d.getDate()+' '+months[d.getMonth()]+' '+d.getFullYear();$('ctime').textContent=d.toLocaleTimeString()}
uclk();
checkSession();
setInterval(uclk,1000);
setInterval(function(){if(loggedIn)rf()},15000);
$('apass').addEventListener('keypress',function(e){if(e.key==='Enter')doLogin()});